"""
Alerts — brute-force / credential-stuffing alerts, filter and acknowledge.

alert_type, severity, and evidence are all generated by our own detector
(honeypot/detectors/async_detection.py) from counts/service names — not
free-form attacker text — but are still rendered via st.dataframe/st.code
rather than markdown interpolation, as a matter of consistent practice.
"""

import asyncio
import sys
from pathlib import Path

import streamlit as st
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from dashboard.login import check_authentication, show_login_page, show_user_info
from database.db_async import db

st.set_page_config(page_title="Alerts", page_icon="🚨", layout="wide")

if not check_authentication():
    show_login_page()
    st.stop()

show_user_info()

st.title("🚨 Alerts")

col1, col2 = st.columns(2)
severity_filter = col1.selectbox("Severity", ["All", "CRITICAL", "HIGH", "MEDIUM", "LOW"])
ack_filter = col2.selectbox("Status", ["All", "Unacknowledged", "Acknowledged"])

severity = None if severity_filter == "All" else severity_filter
acknowledged = {"All": None, "Unacknowledged": False, "Acknowledged": True}[ack_filter]

alerts = asyncio.run(db.list_alerts(limit=200, severity=severity, acknowledged=acknowledged))

if not alerts:
    st.info("No alerts match this filter.")
else:
    severity_icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}

    for alert in alerts:
        icon = severity_icon.get(alert["severity"], "⚪")
        with st.container(border=True):
            col1, col2 = st.columns([4, 1])
            with col1:
                st.markdown(f"{icon} **{alert['severity']}** — {alert['alert_type']}")
                st.caption(f"IP: {alert['ip_address']} | {alert['created_at']}")
                st.code(alert.get("evidence") or "{}", language="json")
            with col2:
                acked = bool(alert.get("acknowledged"))
                if acked:
                    st.success("Acknowledged")
                elif st.button("Acknowledge", key=f"ack_{alert['id']}"):
                    asyncio.run(db.acknowledge_alert(alert["id"]))
                    st.rerun()

st.markdown("---")
st.subheader("All Alerts (table view)")
st.dataframe(pd.DataFrame(alerts), width='stretch')
